# cloudbuild-cd.yaml

options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "."]
    timeout: 500s

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "compute", "ssh", "couple-palace-server",
        "--zone", "asia-northeast3-c",
        "--command",
        "docker pull gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA && docker stop my-container || true && docker rm my-container || true && docker run -d -p 5000:5000 --name my-container gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
      ]
images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"