name: Auto Black Format and PR

on:
  pull_request:
    branches:
      - develop/main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Black
        run: pip install black==22.3.0

      - name: Run Black auto format
        run: black .

      - name: Configure Git
        run: |
          git config user.name "gh-action-black"
          git config user.email "action@github.com"